export const GET_MOVIE_DATA_PENDING = "GET_MOVIE_DATA_PENDING";
export const GET_MOVIE_DATA_SUCCESS = "GET_MOVIE_DATA_SUCCESS";
export const GET_MOVIE_DATA_ERROR = "GET_MOVIE_DATA_ERROR";

export const GET_SINGLE_MOVIE_DATA_PENDING = "GET_SINGLE_MOVIE_DATA_PENDING";
export const GET_SINGLE_MOVIE_DATA_SUCCESS = "GET_SINGLE_MOVIE_DATA_SUCCESS";
export const GET_SINGLE_MOVIE_DATA_ERROR = "GET_SINGLE_MOVIE_DATA_ERROR";

export const SEARCH_MOVIE_PENDING = "SEARCH_MOVIE_PENDING";
export const SEARCH_MOVIE_SUCCESS = "SEARCH_MOVIE_SUCCESS";
export const SEARCH_MOVIE_ERROR = "SEARCH_MOVIE_ERROR";
